import './globals.css'

import { JetBrains_Mono } from 'next/font/google'

const jetbrains = JetBrains_Mono({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-jetbrains',
	display: 'swap', // Bu shriftni tez yuklash uchun
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={`${jetbrains.variable}  scroll-smooth`}>
			<body className='bg-[#01192f]'>{children}</body>
		</html>
	)
}
